name: synthetic_agent pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    name: Test
    strategy:
      matrix:
        python-version: [3.10]
        os: [ ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}